#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing, and building your project before committing'

# Check Prettier standards
npm run check-format ||
(
    echo '🤢🤮🤢🤮 Your code is not formatted correctly. 🤢🤮🤢🤮
    Prettier Check Failed. Run `npm run format`, add changes, and try to commit again.'
    exit 1
)

# Check ESLint Standards
npm run check-lint ||
(
    echo '😤🏀👋😤 Your code has ESLint issues. 😤🏀👋😤
    ESLint Check Failed. Fix the issues listed above, add changes, and try to commit again.'
    exit 1
)

# Check TypeScript Types (if applicable)
npm run check-types ||
(
    echo '🤡😂❌🤡 TypeScript type check failed. 🤡😂❌🤡
    Make the changes required to fix the type errors before committing.'
    exit 1
)

# Build the project
npm run build ||
(
    echo '❌👷🔨❌ Build failed. ❌👷🔨❌
    The build failed: View the errors above to see why.'
    exit 1
)

# Success message
echo '✅✅✅✅ All checks passed. Committing changes now. ✅✅✅✅'
